### ISSUE TITLE
H5053 devices use H5041 wifi hub and are not working

### ISSUE THREAD

**Issue by Collin-Sanders** [natekspencer/hacs-govee_ble#4]
Hello,

The README states that H5053 devices are supported but my H5053 devices use the H5041 hub to connect to my wifi. This means that in order for H5053 devices to be supported H5041 would need to be supported.

Thanks!
Collin

**Comment by natekspencer** [comment]
@Collin-Sanders you are right and that is a mistake in the documentation. This will only control bluetooth Govee devices, so neither the H5053 or H5041 will ever be seen by it since they don't advertise bluetooth messages. I'll get the documentation updated so that is removed and that it more clearly states only bluetooth is supported.
